// TamnaIndex — 시드 데이터 (제주 부동산 매물 샘플)
// 실행: bun run src/lib/seed.ts

import { db } from "./db";

const AGENTS = [
  {
    channelId: "UC_jejurealestate",
    channelName: "제주부동산TV",
    channelUrl: "https://youtube.com/@jejurealestate",
    name: "김제주",
    regNo: "제주-2023-0042",
    office: "제주시 노형동 다이온빌 201호",
    expertise: "읍면 단독·전원주택",
    phone: "064-742-1024",
    verified: true,
    plan: "featured" as const,
  },
  {
    channelId: "UC_aewolvillage",
    channelName: "애월부동산채널",
    channelUrl: "https://youtube.com/@aewolvillage",
    name: "박애월",
    regNo: "제주-2022-0188",
    office: "제주시 애월읍 애월로 55",
    expertise: "애월·한림 바다뷰 매물",
    phone: "064-799-3322",
    verified: true,
    plan: "premium" as const,
  },
  {
    channelId: "UC_seogwipolife",
    channelName: "서귀포라이프",
    channelUrl: "https://youtube.com/@seogwipolife",
    name: "이서귀",
    regNo: "서귀-2021-0091",
    office: "서귀포시 서홍동 중앙로 12",
    expertise: "서귀포·중문 주택·상가",
    phone: "064-763-5588",
    verified: true,
    plan: "featured" as const,
  },
  {
    channelId: "UC_jejugoesi",
    channelName: "제주거시기부동산",
    channelUrl: "https://youtube.com/@jejugoesi",
    name: "조한라",
    regNo: null,
    office: "제주시 일도이동",
    expertise: "구옥·돌집 리모델링 매물",
    phone: "010-5521-8842",
    verified: false,
    plan: "free" as const,
  },
  {
    channelId: "UC_seongsantour",
    channelName: "성산관광부동산",
    channelUrl: "https://youtube.com/@seongsantour",
    name: "최성산",
    regNo: "제주-2024-0210",
    office: "서귀포시 성산읍 성산리",
    expertise: "동쪽 해안 관광·상가",
    phone: "064-787-1200",
    verified: true,
    plan: "free" as const,
  },
];

const THUMBS = [
  "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1583608883209-7c6bcebb9c7c?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd311?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=640&h=360&fit=crop",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=640&h=360&fit=crop",
];

interface SeedListing {
  videoId: string;
  title: string;
  channelId: string;
  publishedAt: string; // days ago
  propertyType: any;
  dealType: any;
  priceText: string;
  priceManwon: number;
  areaM2: number | null;
  areaPyeong: number | null;
  zoning: string | null;
  addressText: string;
  region: string;
  lat: number;
  lng: number;
  summary: string;
  highlights: string[];
  keywords: string[];
  themes: any[];
  extractionSource: "ai" | "fallback";
  confidence: number;
  status: "draft" | "published" | "rejected" | "error" | "opted_out";
  priceHistory?: { manwon: number; daysAgo: number }[];
  publishedAt2DaysAgo?: number;
}

const LISTINGS: SeedListing[] = [
  {
    videoId: "aew01",
    title: "[애월] 바다 보이는 구옥 단독, 2억대 리모델링 가능 매물 #단독주택",
    channelId: "UC_aewolvillage",
    publishedAt: 1,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "2억 8,000만원",
    priceManwon: 28000,
    areaM2: 96,
    areaPyeong: 29,
    zoning: "제2종전용주거지역",
    addressText: "제주시 애월읍 광령리 1234",
    region: "애월",
    lat: 33.472,
    lng: 126.328,
    summary:
      "애월 광령리 바다 전망 구옥 단독. 한담해안도로 도보 5분, 리모델링 전제 매물. 남향, 주차 2대 가능.",
    highlights: ["바다뷰", "주차2대", "남향", "리모델링가능"],
    keywords: ["바다뷰", "구옥", "돌담", "주차2대", "애월"],
    themes: ["세컨하우스", "돌집·구옥", "바다뷰"],
    extractionSource: "ai",
    confidence: 0.93,
    status: "published",
    priceHistory: [{ manwon: 32000, daysAgo: 14 }],
    publishedAt2DaysAgo: 2,
  },
  {
    videoId: "aew02",
    title: "애월 바다 앞 전원주택 5억, 통유리 오션뷰 풀옵션 #전원주택",
    channelId: "UC_aewolvillage",
    publishedAt: 2,
    propertyType: "전원주택",
    dealType: "매매",
    priceText: "5억 5,000만원",
    priceManwon: 55000,
    areaM2: 165,
    areaPyeong: 50,
    zoning: "제2종전용주거지역",
    addressText: "제주시 애월읍 애월리 456",
    region: "애월",
    lat: 33.465,
    lng: 126.331,
    summary:
      "애월읍 바다 앞 신축 전원주택. 통유리 오션뷰, 50평 대지, 마당 주차 3대. 한달살이·세컨하우스 최적.",
    highlights: ["바다뷰", "통유리", "마당", "신축", "주차3대"],
    keywords: ["바다뷰", "오션뷰", "통유리", "신축", "마당", "전원주택"],
    themes: ["세컨하우스", "한달살기", "바다뷰"],
    extractionSource: "ai",
    confidence: 0.97,
    status: "published",
    publishedAt2DaysAgo: 1,
  },
  {
    videoId: "hal01",
    title: "한림 협재 인근 단독 3억대, 리모델링한 돌집 #단독주택",
    channelId: "UC_jejurealestate",
    publishedAt: 3,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "3억 2,000만원",
    priceManwon: 32000,
    areaM2: 120,
    areaPyeong: 36,
    zoning: "제2종전용주거지역",
    addressText: "제주시 한림읍 한림리 789",
    region: "한림",
    lat: 33.408,
    lng: 126.258,
    summary:
      "한림읍 협재 해변 도보 10분. 기존 돌집 리모델링 완료, 마당·창고 포함. 읍민 전입 가능 주택.",
    highlights: ["돌담", "마당", "리모델링", "주차2대"],
    keywords: ["구옥", "돌담", "리모델링", "한림", "협재"],
    themes: ["돌집·구옥", "읍면 단독"],
    extractionSource: "ai",
    confidence: 0.89,
    status: "published",
    publishedAt2DaysAgo: 3,
  },
  {
    videoId: "hal02",
    title: "한림 금악 오션뷰 빌라 1억대, 투자용·한달살이 #빌라",
    channelId: "UC_jejurealestate",
    publishedAt: 5,
    propertyType: "빌라",
    dealType: "매매",
    priceText: "1억 8,000만원",
    priceManwon: 18000,
    areaM2: 66,
    areaPyeong: 20,
    zoning: "제2종일반주거지역",
    addressText: "제주시 한림읍 금악리 220",
    region: "한림",
    lat: 33.415,
    lng: 126.245,
    summary:
      "금악리 바다 전망 빌라. 20평, 오픈형 주방, 풀옵션. 한달살이 운영 실적 보유 매물.",
    highlights: ["바다뷰", "풀옵션", "투자용"],
    keywords: ["바다뷰", "한달살기", "빌라", "한림"],
    themes: ["한달살기", "바다뷰"],
    extractionSource: "ai",
    confidence: 0.84,
    status: "published",
    publishedAt2DaysAgo: 4,
  },
  {
    videoId: "jej01",
    title: "제주시 노형동 신축 전원주택 6억, 마당·온수풀 #전원주택",
    channelId: "UC_jejurealestate",
    publishedAt: 1,
    propertyType: "전원주택",
    dealType: "매매",
    priceText: "6억 8,000만원",
    priceManwon: 68000,
    areaM2: 198,
    areaPyeong: 60,
    zoning: "제2종전용주거지역",
    addressText: "제주시 노형동 1234-5",
    region: "노형·연동",
    lat: 33.489,
    lng: 126.471,
    summary:
      "노형동 신축 전원주택. 60평 대지, 온수풀, 마당 정원. 신제주 도심 접근 5분, 외지인 세컨하우스 추천.",
    highlights: ["신축", "마당", "온수", "주차2대"],
    keywords: ["신축", "마당", "온수", "전원주택", "노형동"],
    themes: ["세컨하우스"],
    extractionSource: "ai",
    confidence: 0.95,
    status: "published",
    publishedAt2DaysAgo: 1,
  },
  {
    videoId: "jej02",
    title: "제주시 원도심 구옥 1억대, 리모델링 각 리모델링 #단독주택",
    channelId: "UC_jejugoesi",
    publishedAt: 4,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "1억 5,000만원",
    priceManwon: 15000,
    areaM2: 80,
    areaPyeong: 24,
    zoning: "제3종일반주거지역",
    addressText: "제주시 일도이동 456-2",
    region: "제주시",
    lat: 33.512,
    lng: 126.528,
    summary:
      "제주시 원도심 구옥 단독. 24평, 돌담 보존형 리모델링 추천. 도심 접근성 최상, 외지인 정착용.",
    highlights: ["구옥", "돌담", "리모델링가능"],
    keywords: ["구옥", "돌담", "제주시", "원도심"],
    themes: ["돌집·구옥", "읍면 단독"],
    extractionSource: "fallback",
    confidence: 0.68,
    status: "draft",
  },
  {
    videoId: "jej03",
    title: "제주시 연동 상가 3억, 권리금 5천, 아파트단지 인접 #상가",
    channelId: "UC_jejurealestate",
    publishedAt: 6,
    propertyType: "상가",
    dealType: "매매",
    priceText: "3억 5,000만원 (권리금 5천)",
    priceManwon: 35000,
    areaM2: 99,
    areaPyeong: 30,
    zoning: "상업지역",
    addressText: "제주시 연동 789-1",
    region: "노형·연동",
    lat: 33.485,
    lng: 126.468,
    summary:
      "연동 아파트단지 인접 상가. 30평, 1층 로드상가, 식당 가능. 유동 인구 풍부.",
    highlights: ["권리금포함", "로드상가", "식당가능"],
    keywords: ["상가", "연동", "노형동", "식당"],
    themes: [],
    extractionSource: "ai",
    confidence: 0.91,
    status: "published",
    publishedAt2DaysAgo: 5,
  },
  {
    videoId: "joc01",
    title: "조천 함덕 해변 인근 단독 4억, 바다 도보 3분 #단독주택",
    channelId: "UC_jejurealestate",
    publishedAt: 2,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "4억 2,000만원",
    priceManwon: 42000,
    areaM2: 132,
    areaPyeong: 40,
    zoning: "제2종전용주거지역",
    addressText: "제주시 조천읍 함덕리 1004",
    region: "조천",
    lat: 33.555,
    lng: 126.802,
    summary:
      "함덕 해수욕장 도보 3분. 40평 대지, 남향 단독. 세컨하우스·한달살이 모두 가능, 게스트하우스 운영 경험.",
    highlights: ["바다뷰", "해변도보", "남향", "주차2대"],
    keywords: ["바다뷰", "해변도보", "조천", "함덕"],
    themes: ["세컨하우스", "한달살기", "바다뷰"],
    extractionSource: "ai",
    confidence: 0.92,
    status: "published",
    publishedAt2DaysAgo: 2,
  },
  {
    videoId: "seong01",
    title: "성산 일출봉 인근 상가주택 2억대, 1층 카페 2층 주택 #상가주택",
    channelId: "UC_seongsantour",
    publishedAt: 7,
    propertyType: "상가주택",
    dealType: "매매",
    priceText: "2억 9,000만원",
    priceManwon: 29000,
    areaM2: 120,
    areaPyeong: 36,
    zoning: "상업지역",
    addressText: "서귀포시 성산읍 성산리 99-7",
    region: "성산",
    lat: 33.462,
    lng: 126.938,
    summary:
      "성산 일출봉 인근 상가주택. 1층 카페 영업 가능, 2층 주거. 관광 특구, 외지인 창업 추천.",
    highlights: ["관광특구", "카페가능", "주거겸용"],
    keywords: ["상가주택", "성산", "일출봉", "카페"],
    themes: [],
    extractionSource: "ai",
    confidence: 0.88,
    status: "published",
    publishedAt2DaysAgo: 6,
  },
  {
    videoId: "seog01",
    title: "서귀포 법환 바다뷰 전원주택 7억, 풀옵션 신축 #전원주택",
    channelId: "UC_seogwipolife",
    publishedAt: 3,
    propertyType: "전원주택",
    dealType: "매매",
    priceText: "7억 2,000만원",
    priceManwon: 72000,
    areaM2: 230,
    areaPyeong: 70,
    zoning: "제2종전용주거지역",
    addressText: "서귀포시 법환동 200-3",
    region: "서귀포",
    lat: 33.248,
    lng: 126.512,
    summary:
      "법환 바다 전망 신축 전원주택. 70평 대지, 풀옵션, 온수풀, 외국인 거주 적합. 하이엔드 세컨하우스.",
    highlights: ["바다뷰", "신축", "온수", "풀옵션", "외국인적합"],
    keywords: ["바다뷰", "오션뷰", "신축", "서귀포", "전원주택"],
    themes: ["세컨하우스", "바다뷰"],
    extractionSource: "ai",
    confidence: 0.96,
    status: "published",
    publishedAt2DaysAgo: 3,
  },
  {
    videoId: "seog02",
    title: "서귀포 원도심 구옥 2억대, 돌담 보존 리모델링 #단독주택",
    channelId: "UC_jejugoesi",
    publishedAt: 4,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "2억 3,000만원",
    priceManwon: 23000,
    areaM2: 90,
    areaPyeong: 27,
    zoning: "제3종일반주거지역",
    addressText: "서귀포시 서홍동 55-8",
    region: "서귀포",
    lat: 33.247,
    lng: 126.561,
    summary:
      "서귀포 원도심 돌담 구옥. 27평, 보존형 리모델링 추천. 원도심 카페·상권 도보권, 정착용 주택.",
    highlights: ["구옥", "돌담", "리모델링가능", "원도심"],
    keywords: ["구옥", "돌담", "서귀포", "원도심"],
    themes: ["돌집·구옥", "읍면 단독"],
    extractionSource: "fallback",
    confidence: 0.71,
    status: "draft",
  },
  {
    videoId: "jung01",
    title: "중문 관광단지 상가 5억, 1층 로드상가, 권리금 무 #상가",
    channelId: "UC_seogwipolife",
    publishedAt: 8,
    propertyType: "상가",
    dealType: "매매",
    priceText: "5억",
    priceManwon: 50000,
    areaM2: 132,
    areaPyeong: 40,
    zoning: "상업지역",
    addressText: "서귀포시 색달동 1234-8",
    region: "중문",
    lat: 33.241,
    lng: 126.411,
    summary:
      "중문관광단지 1층 로드상가. 40평, 권리금 무, 식당·카페 가능. 관광객 유동 풍부.",
    highlights: ["권리금무", "로드상가", "관광단지"],
    keywords: ["상가", "중문", "관광단지", "식당"],
    themes: [],
    extractionSource: "ai",
    confidence: 0.9,
    status: "published",
    publishedAt2DaysAgo: 7,
  },
  {
    videoId: "nam01",
    title: "남원유원지 인근 단독 3억, 한라산뷰 마당 #단독주택",
    channelId: "UC_jejurealestate",
    publishedAt: 9,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "3억 1,000만원",
    priceManwon: 31000,
    areaM2: 150,
    areaPyeong: 45,
    zoning: "제2종전용주거지역",
    addressText: "서귀포시 남원읍 남원리 567",
    region: "남원",
    lat: 33.273,
    lng: 126.701,
    summary:
      "남원유원지 인근 단독. 45평 대지, 한라산 전망, 마당 주차 2대. 조용한 전원생활 적합.",
    highlights: ["한라산뷰", "마당", "주차2대"],
    keywords: ["남원", "한라산뷰", "마당", "단독주택"],
    themes: ["세컨하우스", "읍면 단독"],
    extractionSource: "ai",
    confidence: 0.87,
    status: "published",
    publishedAt2DaysAgo: 8,
  },
  {
    videoId: "dae01",
    title: "대정 모슬포 토지 3억, 300평, 가파도 전망 #토지",
    channelId: "UC_jejurealestate",
    publishedAt: 10,
    propertyType: "토지",
    dealType: "매매",
    priceText: "3억",
    priceManwon: 30000,
    areaM2: 990,
    areaPyeong: 300,
    zoning: "관리지역",
    addressText: "제주시 대정읍 모슬포리 88-2",
    region: "대정",
    lat: 33.239,
    lng: 126.221,
    summary:
      "모슬포 가파도 전망 토지. 300평, 관리지역, 농가주택 신축 가능. 서남단 조용한 전원 부지.",
    highlights: ["가파도전망", "300평", "농가주택가능"],
    keywords: ["토지", "대정", "모슬포", "전원"],
    themes: ["읍면 단독"],
    extractionSource: "ai",
    confidence: 0.83,
    status: "published",
    publishedAt2DaysAgo: 9,
  },
  {
    videoId: "and01",
    title: "안덕 산방산 인근 전원주택 4억대, 다락·마당 #전원주택",
    channelId: "UC_jejugoesi",
    publishedAt: 5,
    propertyType: "전원주택",
    dealType: "매매",
    priceText: "4억 5,000만원",
    priceManwon: 45000,
    areaM2: 175,
    areaPyeong: 53,
    zoning: "제2종전용주거지역",
    addressText: "서귀포시 안덕면 사계리 77-1",
    region: "안덕",
    lat: 33.248,
    lng: 126.311,
    summary:
      "산방산 인근 전원주택. 53평 대지, 다락방, 마당. 서쪽 해안 도보 10분. 외지인 힐링 세컨하우스.",
    highlights: ["다락", "마당", "산방산인근", "주차2대"],
    keywords: ["안덕", "산방산", "다락", "마당", "전원주택"],
    themes: ["세컨하우스", "읍면 단독"],
    extractionSource: "fallback",
    confidence: 0.74,
    status: "draft",
  },
  {
    videoId: "guj01",
    title: "구좌 세화 인근 단독 1억대, 급매, 투자용 #단독주택",
    channelId: "UC_jejurealestate",
    publishedAt: 2,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "1억 2,000만원",
    priceManwon: 12000,
    areaM2: 70,
    areaPyeong: 21,
    zoning: "제3종일반주거지역",
    addressText: "제주시 구좌읍 세화리 333-4",
    region: "구좌",
    lat: 33.515,
    lng: 126.861,
    summary:
      "구좌 세화 리 단독. 21평, 급매 처분, 리모델링 전제. 투자·임대용 최적가. 2주 전 1억5천→인하.",
    highlights: ["급매", "투자용", "리모델링가능"],
    keywords: ["급매", "구좌", "세화", "투자"],
    themes: ["급매", "읍면 단독"],
    extractionSource: "ai",
    confidence: 0.9,
    status: "published",
    priceHistory: [{ manwon: 15000, daysAgo: 14 }],
    publishedAt2DaysAgo: 1,
  },
  {
    videoId: "pyo01",
    title: "표선 해변 인근 단독 2억대, 한달살이 운영 매물 #단독주택",
    channelId: "UC_seongsantour",
    publishedAt: 6,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "2억 7,000만원",
    priceManwon: 27000,
    areaM2: 110,
    areaPyeong: 33,
    zoning: "제2종일반주거지역",
    addressText: "서귀포시 표선면 표선리 12-3",
    region: "표선",
    lat: 33.322,
    lng: 126.821,
    summary:
      "표선 해변 도보 5분 단독. 33평, 한달살이 운영 중, 수익형 매물. 외지인 투자·운영 겸용.",
    highlights: ["해변도보", "한달살이운영", "수익형"],
    keywords: ["표선", "한달살기", "해변도보", "수익형"],
    themes: ["한달살기", "읍면 단독"],
    extractionSource: "ai",
    confidence: 0.86,
    status: "published",
    publishedAt2DaysAgo: 5,
  },
  {
    videoId: "aew03",
    title: "애월 곽지 단독 8천만원, 토지+건물, 급매 처분 #단독주택",
    channelId: "UC_jejugoesi",
    publishedAt: 1,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "8,000만원",
    priceManwon: 8000,
    areaM2: 60,
    areaPyeong: 18,
    zoning: "제3종일반주거지역",
    addressText: "제주시 애월읍 곽지리 401",
    region: "애월",
    lat: 33.478,
    lng: 126.342,
    summary:
      "애월 곽지 단독. 18평, 급매 처분, 상태 보통. 곽지 해변 도보 8분. 첫 매입·임대용 추천.",
    highlights: ["급매", "해변도보", "임대용"],
    keywords: ["급매", "애월", "곽지"],
    themes: ["급매", "읍면 단독"],
    extractionSource: "fallback",
    confidence: 0.62,
    status: "draft",
  },
  {
    videoId: "jej04",
    title: "제주시 아파트 3억, 전세, 24평, 신제주 #아파트",
    channelId: "UC_jejurealestate",
    publishedAt: 4,
    propertyType: "아파트",
    dealType: "전세",
    priceText: "3억 (전세)",
    priceManwon: 30000,
    areaM2: 79,
    areaPyeong: 24,
    zoning: "제1종일반주거지역",
    addressText: "제주시 연동 신화아파지 102동",
    region: "노형·연동",
    lat: 33.482,
    lng: 126.465,
    summary:
      "신제주 아파트 24평 전세. 3억, 도심 접근성 최상, 학군·생활인프라 완비. 외지인 정착용.",
    highlights: ["전세", "학군", "신제주"],
    keywords: ["아파트", "전세", "신제주", "노형동"],
    themes: ["세컨하우스"],
    extractionSource: "ai",
    confidence: 0.94,
    status: "published",
    publishedAt2DaysAgo: 4,
  },
  {
    videoId: "hal03",
    title: "한림 명월리 단독 월세 80만원, 한달살이 가능 #단독주택",
    channelId: "UC_aewolvillage",
    publishedAt: 3,
    propertyType: "단독주택",
    dealType: "월세",
    priceText: "보증금 1,000 / 월 80만원",
    priceManwon: 1000,
    areaM2: 85,
    areaPyeong: 26,
    zoning: "제2종일반주거지역",
    addressText: "제주시 한림읍 명월리 14-2",
    region: "한림",
    lat: 33.421,
    lng: 126.262,
    summary:
      "명월리 단독 월세. 보증금 1천·월세 80만원. 한달살기 협의 가능, 가구 풀옵션. 외지인 단기체류 추천.",
    highlights: ["한달살기가능", "풀옵션", "월세"],
    keywords: ["월세", "한달살기", "한림", "명월리"],
    themes: ["한달살기"],
    extractionSource: "ai",
    confidence: 0.88,
    status: "published",
    publishedAt2DaysAgo: 3,
  },
  {
    videoId: "seog03",
    title: "서귀포 토평 단독 5억대, 한라산뷰 마당 50평 #전원주택",
    channelId: "UC_seogwipolife",
    publishedAt: 11,
    propertyType: "전원주택",
    dealType: "매매",
    priceText: "5억 8,000만원",
    priceManwon: 58000,
    areaM2: 215,
    areaPyeong: 65,
    zoning: "제2종전용주거지역",
    addressText: "서귀포시 토평동 220-7",
    region: "서귀포",
    lat: 33.258,
    lng: 126.578,
    summary:
      "토평 단독 전원주택. 65평 대지, 한라산 전망, 마당 정원. 신축 2년, 외지인 세컨하우스 추천.",
    highlights: ["한라산뷰", "마당", "신축", "주차2대"],
    keywords: ["서귀포", "한라산뷰", "마당", "신축", "전원주택"],
    themes: ["세컨하우스"],
    extractionSource: "ai",
    confidence: 0.92,
    status: "published",
    publishedAt2DaysAgo: 10,
  },
  {
    videoId: "joc02",
    title: "조천 세화 토지 2억, 200평, 관리지역 #토지",
    channelId: "UC_jejurealestate",
    publishedAt: 14,
    propertyType: "토지",
    dealType: "매매",
    priceText: "2억",
    priceManwon: 20000,
    areaM2: 660,
    areaPyeong: 200,
    zoning: "관리지역",
    addressText: "제주시 조천읍 세화리 901-3",
    region: "조천",
    lat: 33.528,
    lng: 126.851,
    summary:
      "조천 세화 토지 200평. 관리지역, 농가주택 신축 가능. 동쪽 해안 접근 용이. 전원 부지.",
    highlights: ["200평", "농가주택가능", "동해안접근"],
    keywords: ["토지", "조천", "세화", "전원"],
    themes: ["읍면 단독"],
    extractionSource: "fallback",
    confidence: 0.7,
    status: "published",
    publishedAt2DaysAgo: 12,
  },
  {
    videoId: "err01",
    title: "성산 광치기 해변 인근 단독 — 자막 추출 실패 (재시도 대기)",
    channelId: "UC_seongsantour",
    publishedAt: 0,
    propertyType: "단독주택",
    dealType: "매매",
    priceText: "추출 실패",
    priceManwon: 0,
    areaM2: null,
    areaPyeong: null,
    zoning: null,
    addressText: "추출 실패",
    region: "성산",
    lat: 33.45,
    lng: 126.93,
    summary: "자막 추출 3회 재시도 실패. fallback 구조화도 실패. 수동 검수 필요.",
    highlights: [],
    keywords: [],
    themes: [],
    extractionSource: "fallback",
    confidence: 0.1,
    status: "error",
  },
];

const COLLECTION_JOBS = [
  {
    trigger: "cron" as const,
    region: "애월·한림",
    found: 8,
    processed: 7,
    failed: 1,
    daysAgo: 0,
    hour: 8,
  },
  {
    trigger: "cron" as const,
    region: "제주시·노형",
    found: 12,
    processed: 11,
    failed: 1,
    daysAgo: 0,
    hour: 8,
  },
  {
    trigger: "cron" as const,
    region: "서귀포·중문",
    found: 6,
    processed: 5,
    failed: 1,
    daysAgo: 0,
    hour: 8,
  },
  {
    trigger: "manual" as const,
    region: "조천·구좌",
    found: 5,
    processed: 5,
    failed: 0,
    daysAgo: 1,
    hour: 14,
  },
  {
    trigger: "cron" as const,
    region: "남원·표선",
    found: 4,
    processed: 3,
    failed: 1,
    daysAgo: 1,
    hour: 8,
  },
];

function daysAgoISO(days: number, hour = 0): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d;
}

async function main() {
  console.log("🌱 TamnaIndex 시드 시작...");

  // 기존 데이터 삭제
  await db.favorite.deleteMany();
  await db.listing.deleteMany();
  await db.agent.deleteMany();
  await db.collectionJob.deleteMany();
  await db.optOut.deleteMany();

  // 중개사
  for (const a of AGENTS) {
    await db.agent.create({ data: a });
  }
  console.log(`✓ 중개사 ${AGENTS.length}건`);

  // 매물
  let listingCount = 0;
  for (const l of LISTINGS) {
    const priceHistory = (l.priceHistory ?? []).map((p) => ({
      manwon: p.manwon,
      at: daysAgoISO(p.daysAgo).toISOString(),
    }));
    await db.listing.create({
      data: {
        videoId: l.videoId,
        videoUrl: `https://youtube.com/watch?v=${l.videoId}`,
        thumbnailUrl: THUMBS[listingCount % THUMBS.length],
        title: l.title,
        channelId: l.channelId,
        publishedAt: daysAgoISO(l.publishedAt),
        collectedAt: daysAgoISO(l.publishedAt),
        propertyType: l.propertyType,
        dealType: l.dealType,
        priceText: l.priceText,
        priceManwon: l.priceManwon,
        priceHistory: JSON.stringify(priceHistory),
        areaM2: l.areaM2,
        areaPyeong: l.areaPyeong,
        zoning: l.zoning,
        addressText: l.addressText,
        region: l.region,
        lat: l.lat,
        lng: l.lng,
        geohash: null,
        summary: l.summary,
        highlights: JSON.stringify(l.highlights),
        keywords: JSON.stringify(l.keywords),
        themes: JSON.stringify(l.themes),
        extractionSource: l.extractionSource,
        confidence: l.confidence,
        status: l.status,
        reviewedBy: l.status === "published" ? "editor" : null,
        publishedAt2: l.publishedAt2DaysAgo
          ? daysAgoISO(l.publishedAt2DaysAgo)
          : null,
        takedownAt: l.status === "opted_out" ? daysAgoISO(1) : null,
      },
    });
    listingCount++;
  }
  console.log(`✓ 매물 ${listingCount}건`);

  // 수집 잡
  for (const j of COLLECTION_JOBS) {
    await db.collectionJob.create({
      data: {
        trigger: j.trigger,
        region: j.region,
        found: j.found,
        processed: j.processed,
        failed: j.failed,
        items: JSON.stringify(
          Array.from({ length: Math.min(j.found, 4) }).map((_, i) => ({
            videoId: `seed_${j.region}_${i}_${j.daysAgo}_${j.hour}`,
            step: i === j.found - 1 && j.failed > 0 ? "transcript" : "saved",
            source: i % 2 === 0 ? "socialkit" : "youtube",
            status: i === j.found - 1 && j.failed > 0 ? "fail" : "ok",
          })),
        ),
        startedAt: daysAgoISO(j.daysAgo, j.hour),
        finishedAt: daysAgoISO(j.daysAgo, j.hour + 1),
      },
    });
  }
  console.log(`✓ 수집잡 ${COLLECTION_JOBS.length}건`);

  // 옵트아웃 샘플 1건
  await db.optOut.create({
    data: {
      key: "UC_optedout_channel",
      reason: "중개사 요청 — 영상 노출 중단",
      requestedBy: "agent",
      at: daysAgoISO(2),
    },
  });
  console.log("✓ 옵트아웃 1건");

  console.log("🎉 TamnaIndex 시드 완료!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
